name: Build and Push to GHCR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image names
        run: |
          echo "SCHEDULER_IMAGE=ghcr.io/${{ github.repository }}:latest" >> $GITHUB_ENV

      - name: Build and push scheduler image
        run: |
          docker build -t $SCHEDULER_IMAGE .
          docker push $SCHEDULER_IMAGE
